cleanup towards 'make test' working. (#30)
* Fix Makefile so mosb and mosctl get built.

The default target had become 'zot'. That meant mosb
or mosctl were not built. Reorder targets and add zot and oras
to the 'all' target.

* Cleanup / Workflow changes towards a working 'make test'.

There are a lot of changes to the workflow file here that
ultimately result in being closer to getting 'make test'
to pass on github workflow.

Fixes:
 * Drop the 'ref: main' from checkout@v3 - this was causing us
   to actually build main even in someone's pull request.
 * add ~/bin to PATH via GITHUB_ENV - doing it once means it
   is there for all sections.
 * install packages for 'make test' to succeed:
    * libarchive-tools for bsdtar
    * squashfuse
    * umoci
 * install skopeo from project-machine/tools release,
   I think the snap was causing the newuidmap/newgidmap issues due
   to apparmor and the setuid on those files.
 * provide git with author and committer via environment vars.
   GIT_COMMITTER_AUTHOR / GIT_COMMITTER_EMAIL and
   GIT_AUTHOR_NAME / GIT_AUTHOR_EMAIL
	export GIT_AUTHOR_NAME="$me" GIT_COMMITTER_NAME="$me"

Cleanup:
 * do not install golang via apt, as we're using it via setup-go@v3.
 * drop some debug-like statements.

* Set a 20 minute timeout on 'make test'

Using 'timeout' was preferable to me compared to
jobs.<job_id>.timeout-minutes.  Testing showed that putting a
'timeout-minutes' on a jobs.<job_id>.steps.<step> did work, but
I liked the control of 'timeout'.  I think the github action
was killed with SIGKILL as no additional output of bats was shown.

* Set up lxc.conf, lxc test changes

Basically:
 * Write a lxc.conf for the running user so they can execute
   unpriv lxc.
 * Put a timeout on 'lxc-wait' calls
 * Remove one use of expect, replacing it with '-y' to
   add-apt-repository.
 * make tests/create-test-container.bash run with '-e' so
   it fails fast.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,10 +7,12 @@ jobs:
     name: build
     runs-on: ubuntu-22.04
     steps:
+      - name: Set up environment
+        run: |
+          mkdir ~/bin
+          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
       - name: Check out git
         uses: actions/checkout@v3
-        with:
-          ref: main
       - name: Set up golang
         uses: actions/setup-go@v3
         with:
@@ -18,26 +20,55 @@ jobs:
       - name: install dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install bats cryptsetup-bin golang libacl1-dev libcryptsetup-dev libgpgme-dev libcap-dev libdevmapper-dev liblxc-dev libpam0g-dev libseccomp-dev libsquashfs-dev lxc lxc-dev make openssl uidmap
-          which newuidmap
-          which newgidmap
+          sudo apt-get install \
+            bats cryptsetup-bin libacl1-dev libarchive-tools \
+            libcryptsetup-dev libgpgme-dev libcap-dev \
+            libdevmapper-dev liblxc-dev libpam0g-dev \
+            libseccomp-dev libsquashfs-dev lxc lxc-dev \
+            make openssl squashfuse uidmap umoci
+      - name: setup lxc
+        run: |
+          chmod ugo+x $HOME
           cat /etc/subuid /etc/subgid
-          sudo snap install --devmode --edge skopeo
+          u=$(id -un) && g=$(id -gn)
+          echo "u=$u g=$g"
+          uidmap=$(awk -F: '$1 == u { print $2, $3 }' "u=$u" /etc/subuid)
+          gidmap=$(awk -F: '$1 == g { print $2, $3 }' "g=$g" /etc/subgid)
+          if [ "$u" = "runner" ] && [ -z "$gidmap" ]; then
+            # 'id -gn' shows docker, but 'runner' is in subgid
+            g="runner"
+            gidmap=$(awk -F: '$1 == g { print $2, $3 }' "g=$g" /etc/subgid)
+          fi
+          echo "uidmap=$uidmap."
+          echo "gidmap=$gidmap."
+          [ -n "$uidmap" ] && [ -n "$gidmap" ] ||
+              { echo "did not get uidmap or gidmap for u=$u g=$g"; exit 1; }
+          mkdir -p ~/.config/lxc/
+          echo "writing .config/lxc/default.conf"
+          tee ~/.config/lxc/default.conf <<EOF
+          lxc.include = /etc/lxc/default.conf
+          lxc.idmap = u 0 $uidmap
+          lxc.idmap = g 0 $gidmap
+          EOF
+
+          echo "writing /etc/lxc/lxc-usernet"
+          echo "$u veth lxcbr0 100" | sudo tee -a /etc/lxc/lxc-usernet
       - name: install stacker
         run: |
-          mkdir -p ~/bin
-          wget -O ~/bin/stacker https://github.com/project-stacker/stacker/releases/download/v1.0.0-rc2/stacker
+          wget -O ~/bin/stacker --progress=dot:mega https://github.com/project-stacker/stacker/releases/download/v1.0.0-rc2/stacker
           chmod 755 ~/bin/stacker
+      - name: install skopeo
+        run: |
+          wget -O ~/bin/skopeo --progress=dot:mega https://github.com/project-machine/tools/releases/download/v0.0.1/skopeo
+          chmod 755 ~/bin/skopeo
       - name: make
         run: |
-          pwd
-          find .
           go get -v ./...
           make
       - name: test
         run: |
-          export PATH=~/bin:$PATH
-          make test || true # ignore odd newgidmap $PATH breakage
+          timeout 20m make test ||
+              echo "Ignoring error in 'make test' [exit code $?]"
       - name: Release
         uses: softprops/action-gh-release@v1
         if: startsWith(github.ref, 'refs/tags/')
